

  #应用配置,公共配置
spring:
  profiles:
    active: dev



---
  #生产环境


spring:
  config:
    activate:
      on-profile: pro
server:
  port: 81
---
  #开发环境
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 82
---
  #测试环境
spring:
  config:
    activate:
      on-profile: test
server:
  port: 83