#配置数据库连接信息
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/db1?serverTimezone=GMT
#    username: root
#    password: 123
#    type: com.alibaba.druid.pool.DruidDataSource


spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db1?serverTimezone=UTC
      username: root
      password: 123
